language: python

python:
  - 2.6
  - 2.7
  - 3.3
matrix:
  allow_failures:
    - python: 2.6
env:
  - TMUX_VERSION=master
  - TMUX_VERSION=1.8
before_install:
 - sudo apt-get update -qq
install:
  - "pip install -e ."
before_script:
  - sudo apt-get install -qq libevent-dev libncurses-dev
  - git clone git://git.code.sf.net/p/tmux/tmux-code tmux
  - cd tmux
  - git checkout $TMUX_VERSION
  - sh autogen.sh
  - ./configure && make && sudo make install
  - cd ..
  - tmux -V
#script: python run_tests.py
script: python setup.py test
